
//Si on veut comparer, le c with classes, avec le c--, avec le objetive c, avec le c normal, il faut etre calme.
//java est un langage de programmation orienté objet, tandis que c est un langage de programmation procédural. Le c-- est une version simplifiée du c, tandis que l'objectif c est une extension du c qui ajoute des fonctionnalités orientées objet. Le java a une syntaxe plus stricte et une gestion de la mémoire plus complexe que le c, qui est plus flexible mais nécessite une gestion manuelle de la mémoire. En termes de performance, le c peut être plus rapide que le java dans certains cas, mais le java offre une meilleure portabilité et une plus grande facilité d'utilisation pour les développeurs.
//java est orienté onjet, impératif, fonctionnel, concurrent, fortement typé, avec ramasse-miettes, lorsqu'on clique sur afficher la definitn, on contniue sur des fihciers en java, et on peut voir les classes, les méthodes, les variables, etc. On peut aussi voir les annotations comme @Override, @Deprecated, etc. qui donnent des informations sur le code. En cliquant sur afficher la définition d'une classe ou d'une méthode, on peut voir son code source et comprendre comment elle fonctionne. Cela permet de mieux comprendre le fonctionnement du code et de faciliter le développement de mods pour Minecraft en utilisant Java.

// Le code source de minecraft est écrit en java, et les mods pour minecraft sont généralement développés en java également, car ils utilisent l'API de minecraft qui est écrite en java. Cependant, il est possible d'utiliser d'autres langages de programmation pour développer des mods pour minecraft, comme le c++ ou le python, en utilisant des outils de transpilation ou des wrappers pour interagir avec l'API de minecraft. Cependant, cela peut être plus complexe et moins performant que d'utiliser directement le java pour développer des mods pour minecraft.
//Donc on ne connait pas le code source de minecraft, mais on peut utiliser des outils de décompilation pour voir le code source de minecraft et comprendre comment il fonctionne. Cela peut être utile pour les développeurs de mods pour minecraft, car cela leur permet de mieux comprendre l'API de minecraft et de créer des mods plus efficaces et compatibles avec le jeu. Cependant, il est important de respecter les droits d'auteur et les licences associées au code source de minecraft, et de ne pas utiliser le code source à des fins commerciales ou illégales.
// L'api de minecraft a été crée par mojang, depuis la version 1.13, avant, les gens du 1er mod loader ont du le créer a partir 


//AIDE JAVA.

//Personne ne confond le java avec le typescript, car le java est un langage de programmation orienté objet, tandis que le typescript est un langage de programmation qui ajoute des types statiques au javascript. Le java est utilisé pour développer des applications mobiles, des applications web, des jeux vidéo, etc., tandis que le typescript est principalement utilisé pour développer des applications web côté client et côté serveur. Le java a une syntaxe plus stricte et une gestion de la mémoire plus complexe que le typescript, qui est plus flexible et plus facile à apprendre pour les débutants.

//Un commentaire en java se fait avec // pour une ligne, ou avec /* */ pour plusieurs lignes.
/// Les classes sont définies avec le mot-clé "class", suivi du nom de la classe et de son contenu entre accolades {}.
//Les méthodes sont définies à l'intérieur des classes, avec un type de retour, un nom de méthode, des paramètres entre parenthèses () et un corps de méthode entre accolades {}.
//Les variables sont déclarées avec un type, un nom et une valeur optionnelle, par exemple : int x = 5; ou String name = "Alice";.
//public veut dire que la classe, la méthode ou la variable est accessible depuis n'importe où, tandis que private signifie qu'elle n'est accessible que depuis la classe elle-même.
//static signifie que la méthode ou la variable appartient à la classe elle-même, plutôt qu'à une instance de la classe. On peut accéder à une méthode statique sans créer d'objet de la classe.
//A l'inverse, une méthode non statique (instance method) nécessite la création d'un objet de la classe pour être appelée.
// final signifie que la variable ne peut pas être modifiée après son initialisation, ou que la méthode ne peut pas être surchargée dans une sous-classe. C'est une constante ou une méthode finale.
//onUse est une méthode qui est appelée lorsqu'un joueur interagit avec un bloc ou un objet dans le jeu. Elle prend généralement des paramètres tels que le monde, la position du bloc, l'état du bloc, le joueur et les informations sur l'interaction. Elle retourne une ActionResult qui indique le résultat de l'interaction (par exemple, SUCCESS, PASS ou FAIL).
//@Override est une annotation qui indique que la méthode suivante redéfinit une méthode de la classe parente ou d'une interface. Cela permet au compilateur de vérifier que la signature de la méthode correspond bien à celle de la méthode redéfinie, et d'éviter les erreurs de typographie ou de paramètres. Donc aulieu de récreer une nouvelle funct ion, on peut simplement redéfinir une fonction existante dans la classe parente pour lui donner un comportement spécifique dans la classe enfant.
// DAns un mod mc, on aura besoin de gérer la mémoire avec l'equivalent de malloc et free, qui sont les méthodes d'allocation et de libération de mémoire en c. En java, la gestion de la mémoire est automatique grâce au ramasse-miettes (garbage collector), qui libère la mémoire des objets qui ne sont plus utilisés. Cependant, il est important de faire attention aux références d'objets pour éviter les fuites de mémoire, où des objets restent en mémoire même s'ils ne sont plus nécessaires. Il est également possible d'utiliser des structures de données comme les tableaux ou les collections pour gérer efficacement la mémoire dans un mod mc.
//extends signifie que la classe actuelle hérite des propriétés et des méthodes d'une classe parente. Cela permet de créer une hiérarchie de classes et de réutiliser du code commun. Par exemple, si on a une classe CartModule qui définit des fonctionnalités de base pour les modules de chariot, on peut créer une classe HeightControllerModule qui étend CartModule pour ajouter des fonctionnalités spécifiques au contrôle de la hauteur. La classe HeightControllerModule aura accès à toutes les méthodes et variables de CartModule, en plus de ses propres fonctionnalités.
//type.shouldEmitRedstone() est une méthode qui vérifie si un type de module doit émettre un signal de redstone. Cela peut être utilisé pour déterminer si un module doit interagir avec les circuits de redstone dans le jeu, par exemple pour activer ou désactiver des mécanismes en fonction de l'état du module. Si la méthode retourne true, cela signifie que le module doit émettre un signal de redstone, sinon il ne le fera pas.
//type est une variable qui représente le type de module, généralement une instance d'une classe qui définit les caractéristiques et les comportements du module. Par exemple, dans un mod mc, on pourrait avoir différents types de modules pour les chariots, tels que des modules de propulsion, des modules de stockage, des modules de défense, etc. Chaque type de module aurait ses propres propriétés et méthodes, et la variable type permettrait d'identifier le type de module actuel et d'accéder à ses fonctionnalités spécifiques.
//Registry.register est une méthode utilisée pour enregistrer des éléments, des blocs, des entités ou d'autres objets dans le registre de Minecraft. Cela permet au jeu de reconnaître et d'utiliser ces objets dans le monde du jeu. Par exemple, si on crée un nouveau bloc dans un mod mc, on doit l'enregistrer avec Registry.register pour qu'il puisse être placé et interagir avec les joueurs et les autres éléments du jeu. La méthode prend généralement des paramètres tels que le type d'objet à enregistrer, un identifiant unique (souvent sous la forme d'un ResourceLocation) et l'instance de l'objet lui-même.
//super() est une référence à la classe parente dans une hiérarchie de classes. Lorsqu'on appelle super() dans un constructeur, cela invoque le constructeur de la classe parente pour initialiser les propriétés héritées. Par exemple, si on a une classe CartModule qui étend une classe Module de base, le constructeur de CartModule peut appeler super() pour s'assurer que les propriétés définies dans Module sont correctement initialisées avant d'ajouter des fonctionnalités spécifiques à CartModule. Cela garantit que la classe parente est correctement configurée avant que la classe enfant ne commence à ajouter ses propres comportements. #a comprendre
// onStateReplaced est une méthode qui est appelée lorsqu'un bloc change d'état, par exemple lorsqu'il est détruit, remplacé ou mis à jour. Cette méthode peut être utilisée pour effectuer des actions spécifiques en réponse à ces changements d'état, comme libérer des ressources, mettre à jour des données ou déclencher des événements. Par exemple, si on a un bloc de stockage dans un mod mc, on pourrait utiliser onStateReplaced pour vider l'inventaire du bloc lorsque celui-ci est détruit, afin de ne pas perdre les objets stockés à l'intérieur.
// mais elle est deprecated, ce qui signifie qu'elle est obsolète et ne devrait plus être utilisée. Il est recommandé d'utiliser une méthode alternative pour gérer les changements d'état des blocs, comme onBlockRemoved ou onBlockDestroyedByPlayer, qui offrent des fonctionnalités similaires mais sont plus adaptées aux versions récentes de Minecraft. Il est important de vérifier la documentation de l'API de Minecraft pour trouver la méthode appropriée à utiliser en fonction de la version du jeu et des fonctionnalités spécifiques que l'on souhaite implémenter dans le mod mc.
//pacakage vs import :/ Le mot-clé package est utilisé pour définir le package auquel appartient une classe, tandis que le mot-clé import est utilisé pour importer des classes d'autres packages afin de les utiliser dans la classe actuelle. Par exemple, si on a une classe CartModule dans le package vswe.stevescarts.module, on peut déclarer le package en haut du fichier avec "package vswe.stevescarts.module;", et ensuite importer d'autres classes nécessaires avec "import vswe.stevescarts.entity.CartEntity;" ou "import net.minecraft.nbt.NbtCompound;". Le package organise les classes en groupes logiques, tandis que l'importation permet d'accéder à des classes spécifiques sans avoir à utiliser leur nom complet à chaque fois.
//implements signifie que la classe actuelle implémente une interface, ce qui signifie qu'elle doit fournir des implémentations concrètes pour toutes les méthodes définies dans cette interface. Par exemple, si on a une interface ModuleInterface qui définit des méthodes comme tick(), readFromNbt() et writeToNbt(), une classe CartModule qui implémente ModuleInterface doit fournir des implémentations pour ces méthodes afin de respecter le contrat de l'interface. Cela permet d'assurer que la classe CartModule peut être utilisée de manière interchangeable avec d'autres classes qui implémentent la même interface, offrant ainsi une flexibilité et une extensibilité dans le code du mod mc.
//abstract signifie que la classe est abstraite, ce qui signifie qu'elle ne peut pas être instanciée directement et doit être étendue par d'autres classes pour être utilisée. Une classe abstraite peut contenir des méthodes abstraites, qui sont des méthodes sans implémentation concrète, et des méthodes concrètes, qui ont une implémentation. Par exemple, si on a une classe CartModule qui est abstraite, elle peut définir des méthodes abstraites comme tick() ou readFromNbt(), que les classes qui étendent CartModule doivent implémenter pour fournir un comportement spécifique. Cela permet de créer une hiérarchie de classes où les fonctionnalités communes sont définies dans la classe abstraite, tandis que les détails spécifiques sont laissés aux classes concrètes qui l'étendent.
// @see est une annotation utilisée dans les commentaires Javadoc pour faire référence à d'autres classes, méthodes ou champs qui sont liés au sujet en question. Cela permet de fournir des liens vers des ressources supplémentaires ou des éléments connexes dans la documentation. Par exemple, si on a une classe CartModule qui utilise une méthode de la classe CartEntity, on peut ajouter un commentaire Javadoc avec @see CartEntity pour indiquer que cette classe est pertinente pour comprendre le fonctionnement de CartModule. Cela aide les développeurs à naviguer dans la documentation et à trouver des informations complémentaires sur les classes et les méthodes utilisées dans le mod mc.
//