plugins {
    id "net.fabricmc.fabric-loom-remap" version "1.15"
    id 'java'
}

sourceCompatibility = JavaVersion.VERSION_17
targetCompatibility = JavaVersion.VERSION_17

archivesBaseName = project.archives_base_name
version = project.mod_version
group = project.maven_group

repositories {
    // HTTP FIRST - Workaround for SSL certificate issues with maven.fabricmc.net
    maven {
        name = "FabricHTTP"
        url = "http://maven.fabricmc.net/"
        allowInsecureProtocol = true
    }
    mavenCentral()
    maven {
        name = "CottonMC"
        url = "https://server.bbkr.space/artifactory/libs-release"
        content {
            includeGroup "io.github.cottonmc"
        }
    }
    maven {
        name = "BuildCraft"
        url = "https://mod-buildcraft.com/maven"
        content {
            includeGroup "alexiil.mc.lib"
        }
    }
    maven {
        name = "TechReborn"
        url = "https://maven.techreborn.dev/"
        content {
            includeGroup "TechReborn"
        }
    }
    maven { url = uri("https://maven.fabricmc.net/") }
}

dependencies {
    minecraft "com.mojang:minecraft:1.19.2"
    mappings "net.fabricmc:yarn:1.19.2+build.28:v2"
    modImplementation "net.fabricmc:fabric-loader:0.14.22"

    modImplementation "net.fabricmc.fabric-api:fabric-api:0.76.0+1.19.2"
    modImplementation include("io.github.cottonmc:LibGui:5.4.0+1.19.2")
    modImplementation include("alexiil.mc.lib:libblockattributes-core:0.10.0")
    modImplementation include("alexiil.mc.lib:libblockattributes-fluids:0.10.0")
}

sourceSets {
    main {
        java {
            srcDirs = ["src/main/java"]
        }
        resources {
            srcDirs += ["src/main/generated"]
        }
    }
}

loom {
    runs {
        datagenClient {
            client()
            name "Data Generation"
            vmArg "-Dfabric-api.datagen"
            vmArg "-Dfabric-api.datagen.output-dir=${file("src/main/generated")}"
            vmArg "-Dfabric-api.datagen.strict-validation"

            ideConfigGenerated = true
            runDir "build/datagen"
            source sourceSets.main
        }
    }

    accessWidenerPath = file("src/main/resources/stevescarts.accesswidener")
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 17
}

java {
    withSourcesJar()
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

jar {
    from("LICENSE") {
        rename { "${it}_${archivesBaseName}"}
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
